//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeddingManager.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceDetail
    {
        public int Id { get; set; }
        public int ServiceId { get; set; }
        public Nullable<System.DateTime> DateSuppressed { get; set; }
        public string Details { get; set; }
        public string Location { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
    
        public virtual Service Service { get; set; }
    }
}
